### ISSUE TITLE
api url error is coming

### ISSUE THREAD

**Issue by maaixprt** [bhoriuchi/passport-activedirectory#9]
Here is errors in response:

Cannot GET /login 

post request:
Cannot POST /login

Here is whole code:
```
'use strict';

const express = require('express');

// Constants
const PORT = 3030;

// App
const app = express();
app.get('/', function (req, res) {
  res.send('Hello world\n');
});

var passport = require('passport')
var ActiveDirectoryStrategy = require('passport-activedirectory')

passport.use(new ActiveDirectoryStrategy({
  integrated: false,
  ldap: {
    url: 'ldap://my.domain.com',
    baseDN: 'DC=my,DC=domain,DC=com',
    username: 'readuser@my.domain.com',
    password: 'readuserspassword'
  }
}, function (profile, ad, done) {
  ad.isUserMemberOf(profile._json.dn, 'AccessGroup', function (err, isMember) {
    if (err) return done(err)
    return done(null, profile)
  })
}))

var opts = { failWithError: true }
app.post('/login', passport.authenticate('ActiveDirectory', opts), function(req, res) {
  res.json(req.user)
}, function (err) {
  res.status(401).send('Not Authenticated')
})

app.listen(PORT);
console.log('Running on http://localhost:' + PORT);
```

**Comment by maaixprt** [comment]
Now error is coming: 

```
 curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:3030/login
TypeError: Cannot read property &#39;username&#39; of undefined<br> &nbsp; &nbsp;at Strategy.authenticate (/usr/src/app/node_modules/passport-activedirectory/index.js:99:24)<br> &nbsp; &nbsp;at attempt (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:348:16)<br> &nbsp; &nbsp;at authenticate (/usr/src/app/node_modules/passport/lib/middleware/authenticate.js:349:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:330:12)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/index.js:271:10)

```

**Comment by bhoriuchi** [comment]
try using the bodyParser in your express config? https://expressjs.com/en/resources/middleware/body-parser.html

**Comment by flik** [comment]
same issue with me

**Comment by Thaborak** [comment]
adding bodyParser solved it for me

**Comment by rapterxcode** [comment]
can you show example app.post bodyParser for me please i not sure how to  

how to use bodyparser with authenticate post username , password

Thank a lot
